services:
  srb2:
    build: .
    container_name: srb2-docker-main
    ports:
      - "5029:5029/udp"
    volumes:
      - "./config:/root/.srb2/config"
      - "./addons:/root/.srb2/addons"    # OPTIONAL - For addons and mods
      - "./adedserv.cfg:/root/.srb2/adedserv.cfg"   # OPTIONAL - For configuring server variables. REMINDER - BE SURE TO CREATE THE .CFG FILE BEFORE RUNNING THE CONTAINER