services:
  srb2:
    build: .
    container_name: srb2-docker-main
    ports:
      - "5029:5029/udp"
    volumes:
      - "./config:/config"
      - "./addons:/addons"    # OPTIONAL - For addons and mods
      - "./logs:/logs"    # Just Logs
      - "./adedserv.cfg:/data/.srb2/adedserv.cfg"   # OPTIONAL - For configuring server variables. REMINDER - BE SURE TO CREATE THE .CFG FILE BEFORE RUNNING THE CONTAINER